from .path import (
    CCIMAR11_DIR,
    CCIMAR11_PATH,
    TEMPLATE_TEST1_PATH,
    TEMPLATE_TEST2_PATH,
    TEMPLATE_TEST3_PATH,
    OBJETIVOS_NAVAIS_PATH,
    MAT_RELEV_CRIT_PATH,
    CONFIG_PAINT_PATH
    )